# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'interface.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(QMainWindow):
    def setupUi(self, QMainWindow):
        if not QMainWindow.objectName():
            QMainWindow.setObjectName(u"MainWindow")
        QMainWindow.resize(800, 600)
        self.centralwidget = QWidget(QMainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(110, 230, 41, 41))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(150, 230, 41, 41))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(190, 230, 41, 41))
        self.pushButton_5 = QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(310, 230, 41, 41))
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(230, 230, 41, 41))
        self.pushButton_7 = QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(350, 230, 41, 41))
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(270, 230, 41, 41))
        self.pushButton_9 = QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(430, 230, 41, 41))
        self.pushButton_10 = QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(470, 230, 41, 41))
        self.pushButton_11 = QPushButton(self.centralwidget)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(510, 230, 41, 41))
        self.pushButton_12 = QPushButton(self.centralwidget)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(390, 230, 41, 41))
        self.pushButton_13 = QPushButton(self.centralwidget)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(550, 230, 41, 41))
        self.pushButton_14 = QPushButton(self.centralwidget)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(280, 270, 41, 41))
        self.pushButton_15 = QPushButton(self.centralwidget)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(370, 310, 41, 41))
        self.pushButton_16 = QPushButton(self.centralwidget)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(200, 270, 41, 41))
        self.pushButton_17 = QPushButton(self.centralwidget)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(320, 270, 41, 41))
        self.pushButton_18 = QPushButton(self.centralwidget)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(290, 310, 41, 41))
        self.pushButton_19 = QPushButton(self.centralwidget)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(120, 270, 41, 41))
        self.pushButton_20 = QPushButton(self.centralwidget)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(240, 270, 41, 41))
        self.pushButton_21 = QPushButton(self.centralwidget)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(410, 310, 41, 41))
        self.pushButton_22 = QPushButton(self.centralwidget)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(330, 310, 41, 41))
        self.pushButton_23 = QPushButton(self.centralwidget)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(450, 310, 41, 41))
        self.pushButton_24 = QPushButton(self.centralwidget)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(530, 310, 41, 41))
        self.pushButton_25 = QPushButton(self.centralwidget)
        self.pushButton_25.setObjectName(u"pushButton_25")
        self.pushButton_25.setGeometry(QRect(160, 270, 41, 41))
        self.pushButton_26 = QPushButton(self.centralwidget)
        self.pushButton_26.setObjectName(u"pushButton_26")
        self.pushButton_26.setGeometry(QRect(490, 310, 41, 41))
        self.pushButton_27 = QPushButton(self.centralwidget)
        self.pushButton_27.setObjectName(u"pushButton_27")
        self.pushButton_27.setGeometry(QRect(440, 270, 41, 41))
        self.pushButton_28 = QPushButton(self.centralwidget)
        self.pushButton_28.setObjectName(u"pushButton_28")
        self.pushButton_28.setGeometry(QRect(360, 270, 41, 41))
        self.pushButton_29 = QPushButton(self.centralwidget)
        self.pushButton_29.setObjectName(u"pushButton_29")
        self.pushButton_29.setGeometry(QRect(400, 270, 41, 41))
        self.pushButton_30 = QPushButton(self.centralwidget)
        self.pushButton_30.setObjectName(u"pushButton_30")
        self.pushButton_30.setGeometry(QRect(480, 270, 41, 41))
        self.pushButton_31 = QPushButton(self.centralwidget)
        self.pushButton_31.setObjectName(u"pushButton_31")
        self.pushButton_31.setGeometry(QRect(560, 270, 41, 41))
        self.pushButton_32 = QPushButton(self.centralwidget)
        self.pushButton_32.setObjectName(u"pushButton_32")
        self.pushButton_32.setGeometry(QRect(520, 270, 41, 41))
        self.pushButton_37 = QPushButton(self.centralwidget)
        self.pushButton_37.setObjectName(u"pushButton_37")
        self.pushButton_37.setGeometry(QRect(130, 310, 41, 41))
        self.pushButton_38 = QPushButton(self.centralwidget)
        self.pushButton_38.setObjectName(u"pushButton_38")
        self.pushButton_38.setGeometry(QRect(210, 310, 41, 41))
        self.pushButton_39 = QPushButton(self.centralwidget)
        self.pushButton_39.setObjectName(u"pushButton_39")
        self.pushButton_39.setGeometry(QRect(170, 310, 41, 41))
        self.pushButton_40 = QPushButton(self.centralwidget)
        self.pushButton_40.setObjectName(u"pushButton_40")
        self.pushButton_40.setGeometry(QRect(250, 310, 41, 41))
        self.pushButton_33 = QPushButton(self.centralwidget)
        self.pushButton_33.setObjectName(u"pushButton_33")
        self.pushButton_33.setGeometry(QRect(380, 350, 41, 41))
        self.pushButton_34 = QPushButton(self.centralwidget)
        self.pushButton_34.setObjectName(u"pushButton_34")
        self.pushButton_34.setGeometry(QRect(300, 350, 41, 41))
        self.pushButton_35 = QPushButton(self.centralwidget)
        self.pushButton_35.setObjectName(u"pushButton_35")
        self.pushButton_35.setGeometry(QRect(340, 350, 41, 41))
        self.pushButton_41 = QPushButton(self.centralwidget)
        self.pushButton_41.setObjectName(u"pushButton_41")
        self.pushButton_41.setGeometry(QRect(220, 350, 41, 41))
        self.pushButton_42 = QPushButton(self.centralwidget)
        self.pushButton_42.setObjectName(u"pushButton_42")
        self.pushButton_42.setGeometry(QRect(180, 350, 41, 41))
        self.pushButton_36 = QPushButton(self.centralwidget)
        self.pushButton_36.setObjectName(u"pushButton_36")
        self.pushButton_36.setGeometry(QRect(420, 350, 41, 41))
        self.pushButton_43 = QPushButton(self.centralwidget)
        self.pushButton_43.setObjectName(u"pushButton_43")
        self.pushButton_43.setGeometry(QRect(500, 350, 41, 41))
        self.pushButton_44 = QPushButton(self.centralwidget)
        self.pushButton_44.setObjectName(u"pushButton_44")
        self.pushButton_44.setGeometry(QRect(460, 350, 41, 41))
        self.pushButton_46 = QPushButton(self.centralwidget)
        self.pushButton_46.setObjectName(u"pushButton_46")
        self.pushButton_46.setGeometry(QRect(140, 350, 41, 41))
        self.pushButton_47 = QPushButton(self.centralwidget)
        self.pushButton_47.setObjectName(u"pushButton_47")
        self.pushButton_47.setGeometry(QRect(260, 350, 41, 41))
        QMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(QMainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(QMainWindow)
        self.statusbar.setObjectName(u"statusbar")
        QMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QMainWindow)

        QMetaObject.connectSlotsByName(QMainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"t", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"j", None))
        self.pushButton_16.setText(QCoreApplication.translate("MainWindow", u"e", None))
        self.pushButton_17.setText(QCoreApplication.translate("MainWindow", u"y", None))
        self.pushButton_18.setText(QCoreApplication.translate("MainWindow", u"g", None))
        self.pushButton_19.setText(QCoreApplication.translate("MainWindow", u"q", None))
        self.pushButton_20.setText(QCoreApplication.translate("MainWindow", u"r", None))
        self.pushButton_21.setText(QCoreApplication.translate("MainWindow", u"k", None))
        self.pushButton_22.setText(QCoreApplication.translate("MainWindow", u"h", None))
        self.pushButton_23.setText(QCoreApplication.translate("MainWindow", u"l", None))
        self.pushButton_24.setText(QCoreApplication.translate("MainWindow", u"'", None))
        self.pushButton_25.setText(QCoreApplication.translate("MainWindow", u"w", None))
        self.pushButton_26.setText(QCoreApplication.translate("MainWindow", u";", None))
        self.pushButton_27.setText(QCoreApplication.translate("MainWindow", u"o", None))
        self.pushButton_28.setText(QCoreApplication.translate("MainWindow", u"u", None))
        self.pushButton_29.setText(QCoreApplication.translate("MainWindow", u"i", None))
        self.pushButton_30.setText(QCoreApplication.translate("MainWindow", u"p", None))
        self.pushButton_31.setText(QCoreApplication.translate("MainWindow", u"]", None))
        self.pushButton_32.setText(QCoreApplication.translate("MainWindow", u"[", None))
        self.pushButton_37.setText(QCoreApplication.translate("MainWindow", u"a", None))
        self.pushButton_38.setText(QCoreApplication.translate("MainWindow", u"d", None))
        self.pushButton_39.setText(QCoreApplication.translate("MainWindow", u"s", None))
        self.pushButton_40.setText(QCoreApplication.translate("MainWindow", u"f", None))
        self.pushButton_33.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.pushButton_34.setText(QCoreApplication.translate("MainWindow", u"b", None))
        self.pushButton_35.setText(QCoreApplication.translate("MainWindow", u"n", None))
        self.pushButton_41.setText(QCoreApplication.translate("MainWindow", u"c", None))
        self.pushButton_42.setText(QCoreApplication.translate("MainWindow", u"x", None))
        self.pushButton_36.setText(QCoreApplication.translate("MainWindow", u",", None))
        self.pushButton_43.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.pushButton_44.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.pushButton_46.setText(QCoreApplication.translate("MainWindow", u"z", None))
        self.pushButton_47.setText(QCoreApplication.translate("MainWindow", u"v", None))
    # retranslateUi